Repository InfernalForest/TheNinthCircle, pull requests merged in 2024-05, with the labels that each got.

#281 Fixed cave teleporter bug
  Content/Levels/Level_Scripts/BP_LevelController.uasset
  Content/Levels/Level_Scripts/BP_Tp.uasset
  Content/Levels/Level_Scripts/LoadNextLevelTrigger_Blueprint.uasset
Labels: bug, enhancement

#282 Prototype Level 6
  Content/Levels/Maps/Prototype_Level_6.umap
  Content/Levels/Maps/_GENERATED/RyanWong/Box_176B0AFA.uasset
  Content/Levels/Maps/_GENERATED/RyanWong/Box_6FD119B2.uasset
Labels: Level Design

#284 Statue Soul Box
  Content/Enemy/Blueprint/RW_DUP_BP_EnemyAI.uasset
  Content/Levels/FinishedLevel/Infinity_Blade_Assets/Materials/MI_AngelStatue_Inst.uasset
  Content/Levels/FinishedLevel/Infinity_Blade_Assets/Materials/M_AngelStatue.uasset
  Content/Levels/Level_Scripts/BP_StatueMasterField.uasset
  Content/Levels/Maps/Prototype_Level_3.umap
  Content/Levels/Prefabs/BP_SoulBox.uasset
  Content/Levels/Prefabs/RewardSpawnerStatue.uasset
  Content/Levels/Prefabs/SM_AngelStatue_GeometryCollection.uasset
  Content/Levels/SC_StatueCrumple.uasset
  Content/Levels/SC_StatueDestroyed_.uasset
  Content/Levels/statue_crumble.uasset
  Content/Levels/statue_crumble_1.uasset
  Content/Levels/statue_crumble_2.uasset
Labels: enhancement, Feature

#288 Texture and VFX for Perks
  Content/Levels/Prefabs/RewardSpawner.uasset
  Content/Perks/PerkActors/BP_Armor_Perk.uasset
  Content/Perks/PerkActors/BP_Damage_Perk.uasset
  Content/Perks/PerkActors/BP_DashDistance_Perk.uasset
  Content/Perks/PerkActors/BP_MagSize_Perk.uasset
  Content/Perks/PerkActors/BP_Movement_Perk.uasset
  Content/Perks/PerkActors/BP_Reload_Perk.uasset
  Content/Perks/PerkActors/BP_SuperJumpTimer_Perk.uasset
  Content/Perks/Template/BP_Perk_Template.uasset
  Content/Perks/Template/M_Perk.uasset
  Content/Perks/Template/M_PerkCell.uasset
  Content/Perks/Template/TCom_Rock_CliffVolcanic_2K_albedo.uasset
  Content/Perks/Template/baseCuravatureMap3.uasset
  Content/Perks/Template/baseNormalMap.uasset
  Content/Perks/Template/perksep8.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_ArmourPerk.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_DamagePerk.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_DashPerk.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_MagSize.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_MovementPerk.uasset
  Content/VFX/BlinkAndDashVFX/Materials/Dash_Wind/MI_ReloadPerk.uasset
Labels: enhancement, art

#293 Level 3 update
  Content/Levels/Maps/Persistent_Levels/Persistent_Finished_Level_3.umap
Labels: Level Design

#298 partially added thunder dash, perk needs to be modified to truly give…
  Content/Character/Blueprints/ActorBlueprints/WW_DUP_BP_FirstPersonCharacter.uasset
  Content/Levels/Prefabs/AugmentSpawner.uasset
  Content/Perks/PerkActors/BP_ThunderDash_Augment.uasset
  Content/Perks/PerkComponents/Thunder_Dash_Augment_Component.uasset
Labels: bug
