Repository InfernalForest/TheNinthCircle, pull requests merged in 2024-02, with the labels that each got.

#171 155 adding treasure room
  Content/Art_Models/Perks/BP_Perk_Template.uasset
  Content/Art_Models/Perks/Perk_Actors/BP_Damage_Perk.uasset
  Content/FirstPerson/Blueprints/Character/BP_FirstPersonCharacter.uasset
  Content/Levels/Level_Scripts/Cave_Teleporter.uasset
  Content/Levels/Maps/Prototype_Level_3.umap
  Content/UI/HUD/RewardSelect.uasset
  Content/UI/HUD/RewardSelectBackground.uasset
Labels: enhancement, Level Design, Feature

#172 Getting closer to properly implementing video settings
  Content/UI/MainMenu/DynamicMenu/Dynamic_Menu.umap
  Content/UI/MainMenu/DynamicMenu/SomethingRandom.uasset
  Content/UI/MainMenu/DynamicMenu/Widgets/GameMode_Widget.uasset
  Content/UI/MainMenu/DynamicMenu/Widgets/Options_Widget.uasset
  Content/UI/MainMenu/DynamicMenu/Widgets/VideoSettings_Widget.uasset
Labels: Feature

#196 seamlessly combined jump and superjump into 1 button and shortened th…
  Content/FirstPerson/Blueprints/Character/WW_DUP_BP_FirstPersonCharacter1.uasset
  Content/FirstPerson/Input/Actions/IA_Jump.uasset
Labels: enhancement, balancing
